language: node_js
sudo: required
node_js: stable
cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
script:
  - ./deploy.sh
branch: master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GH_TOKEN}
  local-dir: ./docs/.vuepress/dist/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master